In [1]:
import numpy as np

In [2]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
print a(0)

SyntaxError: invalid syntax (2217353762.py, line 1)

In [4]:
print a0

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a0)? (1754091146.py, line 1)

In [5]:
print a[0]


SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a[0])? (2243008086.py, line 1)

In [6]:
a = np.array([1, 2, 3])

In [7]:
a

array([1, 2, 3])

In [8]:
print([a])

[array([1, 2, 3])]


In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(1)

array([0.])

In [11]:
print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [12]:
np.append(arr, [1,2])

NameError: name 'arr' is not defined

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [15]:
array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

NameError: name 'array' is not defined

In [16]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [17]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [20]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
np.delete(arr, 4)

array([1, 2, 3, 4, 6, 7, 8])

In [22]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [23]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [24]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
data = np.array([1, 2])
data

array([1, 2])

In [26]:
ones = np.ones(2)
ones

array([1., 1.])

In [27]:
data + ones

array([2., 3.])

In [28]:
data * data

array([1, 4])

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

In [30]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [31]:
array_example.ndim

3

In [32]:
array_example.size

24

In [33]:
array_example.shape

(3, 2, 4)

In [34]:
data * 2

array([2, 4])

In [35]:
data * 5

array([ 5, 10])

In [36]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [37]:
A.sum()

4.8595784

In [38]:
A.min()

0.05093587

In [39]:
A.min()

0.05093587

In [40]:
A.max()

0.82485143

In [41]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [42]:
A.min(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [43]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [44]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [45]:
A.std()

0.21392120766089617

In [46]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [47]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.18043325, 0.1066336 ],
       [0.30718341, 0.90916518],
       [0.19800001, 0.6383136 ]])

In [48]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.9331046  0.81830046]
 [0.81384411 0.25572818]
 [0.17032301 0.88030181]]


In [49]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [50]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [51]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [52]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [53]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [54]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [55]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [56]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [57]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [58]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [59]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [60]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [61]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [62]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [63]:
data_col = np.array([[1, 2, 3, 4, 5, 6]])
print(data_col)

[[1 2 3 4 5 6]]


In [64]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [67]:
arr = np.arange(8).reshape((2, 4))
print(arr)

[[0 1 2 3]
 [4 5 6 7]]


In [68]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [69]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [70]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [71]:
print(np.twos((4,3,2)))

AttributeError: module 'numpy' has no attribute 'twos'

In [72]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [73]:
print(np.random.random((4,3,2)))

[[[0.91343017 0.4910833 ]
  [0.55427166 0.14963375]
  [0.93778572 0.00533457]]

 [[0.27463394 0.64338321]
  [0.86393256 0.8619912 ]
  [0.64849759 0.96670118]]

 [[0.56712718 0.85326576]
  [0.30314659 0.47968505]
  [0.86346254 0.13315204]]

 [[0.71420514 0.75751013]
  [0.7112256  0.53807354]
  [0.95037265 0.43252325]]]


In [74]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
import numpy as np

In [77]:
print(np.arange(28))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [78]:
a=np.arange(28)

In [79]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [80]:
b=a.reshape(3,0)

ValueError: cannot reshape array of size 28 into shape (3,0)

In [81]:
b=a.reshape(3,0)
print(b)

ValueError: cannot reshape array of size 28 into shape (3,0)

In [82]:
b=a.reshape(3,0)
print (b)

ValueError: cannot reshape array of size 28 into shape (3,0)

In [83]:
import numpy as np

In [84]:
a=np.arange(28)

In [85]:
b=a.reshape(3,8)

ValueError: cannot reshape array of size 28 into shape (3,8)

In [86]:
b=a.reshape(3,8)
print(b)

ValueError: cannot reshape array of size 28 into shape (3,8)

In [87]:
b=a.reshape(3,7)

ValueError: cannot reshape array of size 28 into shape (3,7)

In [88]:
b=a.reshape(3,9)

ValueError: cannot reshape array of size 28 into shape (3,9)

In [89]:
b=a.reshape(3,2)

ValueError: cannot reshape array of size 28 into shape (3,2)

In [90]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [91]:
b

NameError: name 'b' is not defined

In [92]:
b = a.reshape(3,2)

ValueError: cannot reshape array of size 28 into shape (3,2)

In [93]:
b = np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [94]:
b=np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [95]:
arrsplit = a

In [96]:
print(arrsplit)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [97]:
np.hsplit(arrsplit,3)

ValueError: array split does not result in an equal division

In [98]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [99]:
a=np.arange(1,28,1)

In [100]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [101]:
b = a.reshape(3,2)

In [102]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [103]:
c = b.reshape(3,3)

ValueError: cannot reshape array of size 27 into shape (3,3)

In [104]:
c = b.reshape(9,3)

In [105]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [106]:
c=b[np.newaxis]

In [107]:
c

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24, 25, 26, 27]]])

In [108]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [109]:
c.shape

(1, 3, 9)

In [110]:
b.shape

(3, 9)

In [111]:
c=b.[3,np.newaxis]

SyntaxError: invalid syntax (3041377550.py, line 1)

In [112]:
c=b[3,np.newaxis]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [113]:
c=np.hsplit(a,3)

In [114]:
c

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
 array([19, 20, 21, 22, 23, 24, 25, 26, 27])]

In [115]:
c=np.hsplit(b,3)

In [116]:
c

[array([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [13, 14, 15],
        [22, 23, 24]]),
 array([[ 7,  8,  9],
        [16, 17, 18],
        [25, 26, 27]])]

In [117]:
c.shape

AttributeError: 'list' object has no attribute 'shape'

In [118]:
c.shape

AttributeError: 'list' object has no attribute 'shape'

In [119]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [120]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [121]:
c=b.reshape

In [122]:
c

<function ndarray.reshape>

In [123]:
arr = np.arange(1, 28, 1).reshape((3, 4))
print(arr)

ValueError: cannot reshape array of size 27 into shape (3,4)

In [124]:
arr = np.arange(1, 28, 1).reshape((3, 3))
print(arr)

ValueError: cannot reshape array of size 27 into shape (3,3)

In [125]:
arr = np.arange(28).reshape((3, 4))
print(arr)

ValueError: cannot reshape array of size 28 into shape (3,4)

In [126]:
arr = np.arange(1, 28, 1).reshape((3, 4))
print(arr)

ValueError: cannot reshape array of size 27 into shape (3,4)

In [127]:
c

<function ndarray.reshape>

In [128]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [129]:
c=np.hsplit(b, 3)

In [130]:
c

[array([[ 1,  2,  3],
        [10, 11, 12],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [13, 14, 15],
        [22, 23, 24]]),
 array([[ 7,  8,  9],
        [16, 17, 18],
        [25, 26, 27]])]

In [131]:
arr = np.arange(28).reshape((9, 3))
print(arr)

ValueError: cannot reshape array of size 28 into shape (9,3)

In [132]:
c=a.reshape(3, 3, 3)

In [133]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [134]:
mulai = int(input('Mulai: '))
selesai = int(input('selesai: '))

Mulai: 0
selesai: 1


In [135]:
mulai = int(input('Mulai: '))
selesai = int(input('selesai: '))

a=np.arange(mulai, selesai, 1)
b=a.reshape(3, 9)
c=a.reshape(3, 3, 3)

Mulai: 0
selesai: 12


ValueError: cannot reshape array of size 12 into shape (3,9)

In [136]:
mulai = int(input('Mulai: '))
selesai = int(input('selesai: '))

a=np.arange(mulai, selesai, 1)
b=a.reshape(3, 9)
c=a.reshape(3, 3, 3)

Mulai: 1
selesai: 28


In [137]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [138]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [139]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
mulai = int(input('Mulai: '))
selesai = int(input('selesai: '))

a=np.arange(mulai, selesai, 1)
b=a.reshape(3, 9)
c=a.reshape(3, 3, 3)